
const makeData = [
  {
    subject: 'English',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },

  {
    subject: 'Kiswahili',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'Mathematics',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'Biology',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'Physics',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'History & Govt',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'Geography',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'IRE',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'AGRICULTURE',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'COMPUTER STUDIES',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'BUSINESS STUDIES',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: '',
  },
  {
    subject: 'TOTAL MARKS/POINTS',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: 'highlight',
  },
  {
    subject: 'MEAN SCORE',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: 'highlight',
  },
  {
    subject: 'MEAN GRADE',
    cat: 0,
    main: 0,
    percentage: 0,
    Grade: '',
    Points: 0,
    Remarks: '',
    initials: '',
    className: 'highlight',
  },
];
const totalPercentage = makeData.reduce((acc, obj) => acc + obj.percentage, 0);

console.log(totalPercentage);
export default makeData;
